# Generated by Django 2.2.1 on 2019-05-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('input_image', models.ImageField(upload_to='%Y/%m/%d/')),
                ('style_image', models.ImageField(upload_to='%Y/%m/%d/')),
                ('colored_image', models.ImageField(blank=True, default=None, null=True, upload_to='%Y/%m/%d/')),
                ('style_transfered_image', models.ImageField(blank=True, default=None, null=True, upload_to='neural_style/%Y/%m/%d/')),
                ('visually_similar_image', models.ImageField(blank=True, default=None, null=True, upload_to='%Y/%m/%d/')),
                ('has_failed', models.BooleanField(default=False)),
            ],
        ),
    ]
