# Generated by Django 2.2 on 2019-05-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='neural_output_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='uploads/neural_style/%Y/%m/%d/'),
        ),
    ]
