# Generated by Django 2.2 on 2019-05-12 22:40

from django.db import migrations, models
import image_processor.validators


class Migration(migrations.Migration):

    dependencies = [
        ('image_processor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='st_content_weight_blend',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='image',
            name='st_iterations',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='image',
            name='st_pooling',
            field=models.CharField(choices=[('avg', 'avg'), ('max', 'max')], default='avg', max_length=3),
        ),
        migrations.AddField(
            model_name='image',
            name='st_preserve_colors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='st_style_layer_weight_exp',
            field=models.FloatField(default=1.0, validators=[image_processor.validators.validate_neural_content_weight_blend]),
        ),
    ]
