# Generated by Django 2.2.1 on 2019-05-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='style_transferred_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='%Y/%m/%d/'),
        ),
    ]
