# Generated by Django 2.2 on 2019-05-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processor', '0002_image_neural_output_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='job_id',
            field=models.CharField(default=False, max_length=255),
        ),
    ]
