# Generated by Django 2.2.1 on 2019-05-27 18:30

import os
import json
from django.db import migrations, models
from django.conf import settings

def populate_verses(apps, schema_editor):
    with open(os.path.join(settings.BASE_DIR, "data/verses.json"), "rb") as data_file:
        data = json.load(data_file)
        for verse in data:
            Verse = apps.get_model("image_processor", "Verse")
            v = Verse(text=verse)
            v.save()


class Migration(migrations.Migration):

    dependencies = [
        ('image_processor', '0002_auto_20190520_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.RunPython(populate_verses),
    ]
