# Generated by Django 2.2.1 on 2019-05-27 18:49

from django.db import migrations, models
import django.db.models.deletion
from image_processor.service import populate_available_verses

def populate(apps, schema_editor):
    populate_available_verses(apps.get_model("image_processor", "Verse"), apps.get_model("image_processor", "AvailableVerse"))

class Migration(migrations.Migration):

    dependencies = [
        ('image_processor', '0003_verse'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableVerse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='image_processor.Verse')),
            ],
        ),
        migrations.RunPython(populate),
    ]
