# Generated by Django 2.2.1 on 2019-05-19 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_processor', '0004_auto_20190514_1455'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Artwork',
        ),
    ]
