# Generated by Django 2.2.1 on 2019-06-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processor', '0005_artwork_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
