# Generated by Django 2.2.1 on 2019-05-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processor', '0005_auto_20190519_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='colored_file',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='%Y/%m/%d/'),
        ),
    ]
