# Generated by Django 2.2 on 2019-05-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processor', '0006_auto_20190506_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='has_failed',
            field=models.BooleanField(default=False),
        ),
    ]
