# Generated by Django 2.2.1 on 2019-07-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processor', '0007_artwork_verse'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
